/**
 * /api/classify — single-image scan endpoint.
 *
 * Mirrors the per-image logic in scripts/batch-vlm-classify.mjs but as a
 * Next.js Node-runtime route handler. Accepts a multipart/form-data POST
 * with an `image` field, runs the pipeline, returns a vague `verdict` +
 * `reason` JSON the front-end renders.
 *
 * Pipeline (parallel where possible):
 *   1. C2PA Content Credentials (@contentauth/c2pa-node)
 *   2. Vision LLM #1: Perplexity Sonar Pro (vision + native search)
 *   3. Vision LLM #2: Anthropic Claude Opus 4.7 :online (vision + Exa)
 *   4. Claude OCR + Sonar brand-from-OCR
 *   5. Corner-crop watermark scan (BR + BL, sharp + Claude vision)
 *
 * Verdict: AI is informational only (does NOT block). Brand or watermark
 * blocks. Reason text is one short phrase, no implementation detail.
 */

import { NextRequest, NextResponse } from "next/server";
import sharp from "sharp";
import { Reader as C2paReader } from "@contentauth/c2pa-node";

export const runtime = "nodejs";
export const maxDuration = 60;

const OPENROUTER_KEY = process.env.OPENROUTER_API_KEY;
const OR_URL = "https://openrouter.ai/api/v1/chat/completions";

// ── needles & regexes ────────────────────────────────────────────────────
const AI_GENERATOR_NEEDLES = [
  "dall","openai","chatgpt","sora","firefly","adobe firefly","imagen",
  "midjourney","stable diffusion","stability","sdxl","flux","bing image creator",
  "veo","runway","leonardo","ideogram","playground","nightcafe","gpt",
];
const AI_DIGITAL_SOURCE_NEEDLES = [
  "trainedalgorithmicmedia","trainedalgorithmicdata",
  "compositewithtrainedalgorithmicmedia","algorithmicmedia",
  "algorithmicallyenhanced","compositesynthetic","datadrivenmedia",
];
const NAMED_GENERATORS =
  /gemini|dall|chatgpt|sora|firefly|designer|bing|imagen|midjourney|stability|sdxl|flux|leonardo|ideogram|playground|nightcafe|shutterstock|getty|istock|adobe stock|alamy|dreamstime|depositphotos|stocksy|eyeem|bigstock|reuters|envato|proof|sample|preview|copy|watermark|demo|comp/i;

// ── prompts ──────────────────────────────────────────────────────────────
const VLM_SYSTEM_PROMPT = `You are a content-screening system for a copyright registry. Make THREE independent judgments about the attached image.

JUDGMENT 1 — AI generation (informational only):
Decide whether the image was generated by an AI model versus produced by a human. Use visual tells (hyperreal lighting, anatomy errors, smooth gradients, telltale style fingerprints of MJ / DALL·E / SDXL / Flux / Firefly / Imagen / Sora / Gemini). Use web search if uncertain.

JUDGMENT 2 — Brand presence (BLOCKING):
First enumerate every popular commercial brand or trademarked logo you can identify in brands_detected. Walk every quadrant — signs, neon, storefronts, product labels, shopping bags, clothing, billboards. HARD RULE: if the list has 3+ entries, decision = "block". Also block on a single dominant brand or recreated/derivative trademark (stylized swoosh, fan-art Mickey, fan-Pikachu).

JUDGMENT 3 — Watermark / third-party overlay (BLOCKING):
Scan the four corners pixel-by-pixel. Block on AI-generator stamps (Gemini four-pointed sparkle, DALL·E rainbow stripe, Firefly text, Designer/Bing badge, Sora logo), stock-agency text (Shutterstock/Getty/iStock/Adobe Stock/Alamy/Dreamstime/Envato/etc.), or tiled "PROOF/SAMPLE/PREVIEW" overlays. DO NOT flag celestial elements (sun, moon, stars, sunbursts) in painterly artwork — those are art, not watermarks. DO NOT flag letterbox bars or screenshot framing.

Respond ONLY with JSON, no fences:
{
  "ai_judgment": { "decision": "ai" | "human", "confidence": "high" | "medium" | "low", "tells": [], "reasoning": "" },
  "brand_judgment": { "brands_detected": [{"name":"","evidence":"","confidence":"","verified_via_search":false}], "decision": "block" | "allow", "reasoning": "" },
  "watermark_judgment": { "watermarks_detected": [{"type":"","text":"","is_third_party":false,"tiled_or_repeating":false}], "decision": "block" | "allow", "reasoning": "" }
}`;

const CLAUDE_OCR_PROMPT =
  "Read every readable text string in this image — sign text, neon, product labels, storefront names, banners, captions, written words, AND any faint / translucent / repeated / diagonal watermark text overlays (e.g., 'envato', 'shutterstock', 'getty', 'PROOF', 'SAMPLE', 'PREVIEW' tiled across the image). Return ONLY the raw text strings, one per line, exactly as written. If no readable text exists, respond with the single word: NONE. DO NOT invent text.";

const BRAND_FROM_OCR_PROMPT = `You will receive a list of text strings extracted by an OCR model from an image. Identify which strings name popular commercial brands or trademarked logos. Use web search if uncertain. Respond ONLY in JSON, no fences:
{ "brands": ["..."], "decision": "block" | "allow", "reasoning": "" }
Decision rule: brands.length >= 3 → "block". Else "allow".`;

const CORNER_PROMPT = `This is a corner crop of a larger image, cropped and upscaled so you can examine fine detail.

PRE-CHECK: classify the medium first.
  - Real photograph (city street, real scene) → return watermark_found:false UNLESS you can read a clear stock-agency name as text. Real photos never have AI generator watermarks.
  - Painterly artwork → return watermark_found:false. Suns/stars/sparkles in painted art are art, not watermarks.
  - Photo-realistic AI output → THIS is where Gemini sparkles, DALL·E rainbows, etc. live.

Look for: Gemini sparkle (small four-pointed star, metallic gradient, pasted-on look), DALL·E rainbow stripe (5 colored squares), Firefly text, Designer/Bing badge, Sora text, stock-agency name (Shutterstock/Getty/iStock/Adobe Stock/Alamy/Dreamstime/Envato), or PROOF/SAMPLE/PREVIEW overlay text.

Respond ONLY in JSON:
{ "watermark_found": true|false, "type": "ai_generator"|"stock_agency"|"stock_preview"|"generic_overlay"|"artist_signature"|"other"|null, "specific_mark": null, "text": null, "reasoning": "" }`;

// ── C2PA ─────────────────────────────────────────────────────────────────
type C2paResult = { found: boolean; isAI: boolean; generator: string | null; digitalSourceType: string | null };

function scanManifestStore(store: any): C2paResult {
  const empty: C2paResult = { found: false, isAI: false, generator: null, digitalSourceType: null };
  if (!store?.manifests) return empty;
  const manifests = Object.values(store.manifests) as any[];
  if (manifests.length === 0) return empty;
  const active = store.active_manifest ? store.manifests[store.active_manifest] : null;
  const prettyGenerator =
    active?.claim_generator ||
    active?.claim_generator_info?.[0]?.name ||
    manifests[0]?.claim_generator ||
    manifests[0]?.claim_generator_info?.[0]?.name ||
    null;
  let generatorMatch: string | null = null;
  let digitalSource: string | null = null;
  for (const m of manifests) {
    const blob = [m.claim_generator ?? "", ...(m.claim_generator_info ?? []).map((g: any) => g?.name ?? "")].join(" ").toLowerCase();
    if (!generatorMatch) {
      const hit = AI_GENERATOR_NEEDLES.find((n) => blob.includes(n));
      if (hit) generatorMatch = hit;
    }
    for (const a of m.assertions ?? []) {
      if (!/c2pa\.actions/.test(a.label ?? "")) continue;
      for (const action of a.data?.actions ?? []) {
        const dst = (action.digitalSourceType ?? "").toLowerCase();
        if (AI_DIGITAL_SOURCE_NEEDLES.some((n) => dst.includes(n))) {
          digitalSource = action.digitalSourceType;
          break;
        }
      }
      if (digitalSource) break;
    }
    if (generatorMatch && digitalSource) break;
  }
  return { found: true, isAI: !!generatorMatch || !!digitalSource, generator: prettyGenerator, digitalSourceType: digitalSource };
}

async function readC2pa(buffer: Buffer, mime: string): Promise<C2paResult> {
  try {
    const reader = await C2paReader.fromAsset({ mimeType: mime, buffer });
    if (!reader) return { found: false, isAI: false, generator: null, digitalSourceType: null };
    return scanManifestStore(reader.json());
  } catch {
    return { found: false, isAI: false, generator: null, digitalSourceType: null };
  }
}

// ── OpenRouter helpers ──────────────────────────────────────────────────
async function postOR(body: any) {
  const res = await fetch(OR_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENROUTER_KEY}`,
      "HTTP-Referer": "https://donottrain.vercel.app",
      "X-Title": "Power Pixel Pro",
    },
    body: JSON.stringify(body),
  });
  const json = await res.json();
  if (!res.ok) throw new Error(`${body.model}: ${res.status} ${JSON.stringify(json).slice(0, 200)}`);
  return json;
}

function parseJson(content: string): any {
  const stripped = content.replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/\s*```\s*$/i, "").trim();
  try { return JSON.parse(stripped); }
  catch {
    const m = stripped.match(/\{[\s\S]*\}/);
    if (m) { try { return JSON.parse(m[0]); } catch {} }
    return null;
  }
}

async function callVisionLLM(model: string, dataUrl: string) {
  const json = await postOR({
    model,
    messages: [{
      role: "user",
      content: [
        { type: "text", text: VLM_SYSTEM_PROMPT },
        { type: "image_url", image_url: { url: dataUrl } },
      ],
    }],
    temperature: 0,
    max_tokens: 800,
  });
  const content = json.choices?.[0]?.message?.content ?? "";
  const parsed = parseJson(content) ?? {};
  return {
    ai: parsed.ai_judgment ?? { decision: "human" },
    brand: parsed.brand_judgment ?? { decision: "allow", brands_detected: [] },
    watermark: parsed.watermark_judgment ?? { decision: "allow", watermarks_detected: [] },
  };
}

async function claudeOCR(dataUrl: string): Promise<string> {
  const json = await postOR({
    model: "anthropic/claude-sonnet-4-6",
    messages: [{
      role: "user",
      content: [
        { type: "text", text: CLAUDE_OCR_PROMPT },
        { type: "image_url", image_url: { url: dataUrl } },
      ],
    }],
    temperature: 0,
    max_tokens: 600,
  });
  const content = (json.choices?.[0]?.message?.content ?? "").trim();
  return /^none\.?$/i.test(content) ? "" : content;
}

async function brandFromOCR(ocrText: string) {
  if (!ocrText || ocrText.length < 3) return { decision: "allow", brands: [] };
  const json = await postOR({
    model: "perplexity/sonar-pro",
    messages: [
      { role: "system", content: BRAND_FROM_OCR_PROMPT },
      { role: "user", content: `OCR text from image:\n${ocrText}` },
    ],
    temperature: 0,
    max_tokens: 400,
  });
  const content = json.choices?.[0]?.message?.content ?? "";
  const parsed = parseJson(content) ?? { decision: "allow", brands: [] };
  return parsed;
}

async function cropCorner(buffer: Buffer, corner: "br" | "bl"): Promise<string> {
  const meta = await sharp(buffer).metadata();
  const w = meta.width || 1024;
  const h = meta.height || 1024;
  const cw = Math.max(80, Math.floor(w * 0.30));
  const ch = Math.max(80, Math.floor(h * 0.25));
  const left = corner === "br" ? w - cw : 0;
  const top = h - ch;
  const buf = await sharp(buffer)
    .extract({ left, top, width: cw, height: ch })
    .resize({ width: 768, height: 768, fit: "inside", withoutEnlargement: false })
    .jpeg({ quality: 92 })
    .toBuffer();
  return `data:image/jpeg;base64,${buf.toString("base64")}`;
}

async function checkCornerWatermark(buffer: Buffer, corner: "br" | "bl") {
  try {
    const dataUrl = await cropCorner(buffer, corner);
    const json = await postOR({
      model: "anthropic/claude-sonnet-4-6:online",
      messages: [{
        role: "user",
        content: [
          { type: "text", text: CORNER_PROMPT },
          { type: "image_url", image_url: { url: dataUrl } },
        ],
      }],
      temperature: 0,
      max_tokens: 300,
    });
    const content = json.choices?.[0]?.message?.content ?? "";
    const parsed = parseJson(content) ?? {};
    return {
      corner,
      watermark_found: !!parsed.watermark_found,
      type: parsed.type ?? null,
      specific_mark: parsed.specific_mark ?? null,
    };
  } catch {
    return { corner, watermark_found: false, type: null, specific_mark: null };
  }
}

// ── classify ────────────────────────────────────────────────────────────
async function classify(buffer: Buffer, mime: string) {
  const dataUrl = `data:${mime};base64,${buffer.toString("base64")}`;

  const [c2pa, vlm1, vlm2, ocrText, cBR, cBL] = await Promise.all([
    readC2pa(buffer, mime),
    callVisionLLM("perplexity/sonar-pro", dataUrl),
    callVisionLLM("anthropic/claude-opus-4-7:online", dataUrl),
    claudeOCR(dataUrl),
    checkCornerWatermark(buffer, "br"),
    checkCornerWatermark(buffer, "bl"),
  ]);

  const ocrBrand = await brandFromOCR(ocrText);

  // ── verdict aggregation ──
  const aiDetected =
    c2pa.isAI ||
    vlm1.ai?.decision === "ai" ||
    vlm2.ai?.decision === "ai";

  const brandBlocked =
    vlm1.brand?.decision === "block" ||
    vlm2.brand?.decision === "block" ||
    ocrBrand.decision === "block";

  // Watermark voting (matches batch-vlm-classify):
  //   - Single-LLM block fires if it names a known service
  //   - OR both full-image LLMs agree
  //   - OR a corner crop returns a NAMED match
  const cornerNamed = [cBR, cBL].some(
    (c) =>
      c.watermark_found &&
      typeof c.specific_mark === "string" &&
      NAMED_GENERATORS.test(c.specific_mark)
  );
  const bothLLMsBlockWm =
    vlm1.watermark?.decision === "block" && vlm2.watermark?.decision === "block";
  const namedWmInVlm = [vlm1, vlm2].some((v) => {
    if (v.watermark?.decision !== "block") return false;
    const blob =
      JSON.stringify(v.watermark?.watermarks_detected ?? []) +
      " " +
      (v.watermark?.reasoning ?? "");
    return NAMED_GENERATORS.test(blob);
  });
  const watermarkBlocked = cornerNamed || bothLLMsBlockWm || namedWmInVlm;

  // AI alone does NOT block — informational only. Brand or watermark blocks.
  const blocked = brandBlocked || watermarkBlocked;

  let reason: string | null = null;
  if (blocked) {
    if (brandBlocked && watermarkBlocked) reason = "Brand and watermark detected.";
    else if (brandBlocked) reason = "Trademark or brand presence detected.";
    else reason = "Third-party watermark detected.";
  }

  return {
    verdict: blocked ? "block" : "allow",
    reason,
    ai_detected: aiDetected,
    flags: { ai: aiDetected, brand: brandBlocked, watermark: watermarkBlocked },
  };
}

// ── route handler ───────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  if (!OPENROUTER_KEY) {
    return NextResponse.json({ error: "OPENROUTER_API_KEY not configured" }, { status: 500 });
  }
  try {
    const formData = await req.formData();
    const file = formData.get("image");
    if (!file || !(file instanceof File)) {
      return NextResponse.json({ error: "missing image" }, { status: 400 });
    }
    const buffer = Buffer.from(await file.arrayBuffer());
    const mime = file.type || "image/jpeg";
    const result = await classify(buffer, mime);
    return NextResponse.json(result);
  } catch (e: any) {
    console.error("[classify] error:", e);
    return NextResponse.json({ error: String(e?.message ?? e) }, { status: 500 });
  }
}
